[package]
name = "csv"
version = "0.1.0"
authors = ["Andrew Gallant <jamslam@gmail.com>"]

[[lib]]
name = "csv"
path = "src/lib.rs"
crate_type = ["dylib", "rlib"]

# [dependencies.quickcheck] 
# git = "git://github.com/BurntSushi/quickcheck" 

