[package]
name = "csv"
version = "1.0.0-beta.1"  #:version
authors = ["Andrew Gallant <jamslam@gmail.com>"]
description = "Fast CSV parsing with support for serde."
documentation = "http://burntsushi.net/rustdoc/csv/"
homepage = "https://github.com/BurntSushi/rust-csv"
repository = "https://github.com/BurntSushi/rust-csv"
readme = "README.md"
keywords = ["csv", "comma", "parser", "delimited", "serde"]
license = "Unlicense/MIT"
categories = ["encoding", "parser-implementations"]

[lib]
bench = false

[dependencies]
csv-core = { path = "csv-core", version = "0.1.0" }
serde = "1.0.7"

[dev-dependencies]
serde_derive = "1"
serde_bytes = "0.10"

[profile.release]
debug = true

[profile.bench]
debug = true
