[package]
name = "csv"
version = "0.12.14"  #:version
authors = ["Andrew Gallant <jamslam@gmail.com>"]
description = "CSV parsing with automatic type based decoding and encoding."
documentation = "http://burntsushi.net/rustdoc/csv/"
homepage = "https://github.com/BurntSushi/rust-csv"
repository = "https://github.com/BurntSushi/rust-csv"
readme = "README.md"
keywords = ["csv", "tsv", "comma"]
license = "Unlicense"

[lib]
name = "csv"

[dependencies]
rustc-serialize = "*"

[dev-dependencies]
regex = "*"

[profile.bench]
opt-level = 3
lto = true  # this doesn't seem to work... why?
